# PASS_SET  STEBBINS
# PASSBAND  G
# REFERENCE Stebbins, J. and Whitford A.E., 1943, ApJ 98, 20
# Table taken from ADPS http://ulisse.pd.astro.it/Astro/ADPS/Systems/index.html         
 4900   0.0    
 5000  18.6    
 5100  30.8    
 5200  36.3    
 5300  38.8    
 5400  39.1    
 5500  38.0    
 5600  35.4    
 5700  32.7    
 5800  29.6    
 5900  26.3    
 6000  23.3    
 6100  19.9    
 6200  17.1    
 6300  14.0    
 6400  11.6    
 6500   9.4    
 6600   7.4    
 6700   5.9    
 6800   4.4    
 6900   3.5    
 7000   2.7         
 7100   2.0                        
 7200   1.5                        
 7300   0.9                        
 7400   0.5                        
 7500   0.0                        
                                   
                                   
                                   
                               
                               
                               
                               
                               
                               
                               
                               
                               
                               
                               
                               
                               
                               
                               
                               
                               
                               
                               
                               
                               
                               
                               
                               
                               
                               
                               
                               
                               
                               