# PASS_SET  STEBBINS
# PASSBAND  V
# REFERENCE Stebbins, J. and Whitford A.E., 1943, ApJ 98, 20
# Table taken from ADPS http://ulisse.pd.astro.it/Astro/ADPS/Systems/index.html         
   3600   0.0    
   3700  10.7    
   3800  26.4    
   3900  38.0    
   4000  44.8    
   4100  47.7    
   4200  45.0    
   4300  40.8    
   4400  35.1    
   4500  31.0    
   4600  25.2    
   4700  18.3    
   4800  10.4    
   4900   4.4    
   5000   1.0    
   5100   0.0    
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 
                 